package openingrouter

// OpenRouterResponse is the root response of endpoints wrapping their payload in
// a data object.
type OpenRouterResponse[T any] struct {
	Data T `json:"data"`
}

// ContentPartImage represents an image content part, as a base64 data url or an
// HTTP(S) url.
type ContentPartImage struct {
	Type     ContentPartType     `json:"type"`
	ImageURL ContentPartImageURL `json:"image_url"`
}

// ContentPartImageURL holds the url of a ContentPartImage.
type ContentPartImageURL struct {
	URL string `json:"url"`
}

// ProviderPreferences represents the provider routing preferences and provider
// specific passthrough configuration of a request. Order, Only and Ignore are
// merged with the account-wide settings.
type ProviderPreferences struct {
	Order          []string            `json:"order,omitempty"`
	Only           []string            `json:"only,omitempty"`
	Ignore         []string            `json:"ignore,omitempty"`
	AllowFallbacks *bool               `json:"allow_fallbacks,omitempty"`
	Sort           *ProviderSortConfig `json:"sort,omitempty"`
	Options        ProviderOptions     `json:"options,omitempty"`
}

// ProviderSortConfig represents the sorting strategy used for a request when no
// explicit order is given. Setting it disables load balancing.
type ProviderSortConfig struct {
	By        ProviderSort          `json:"by,omitempty"`
	Partition ProviderSortPartition `json:"partition,omitempty"`
}

// ProviderOptions holds provider specific options keyed by provider slug. Only
// the options of the matched provider are forwarded, the rest are ignored and
// unrecognized keys are silently dropped.
type ProviderOptions map[string]map[string]any

// Usage represents the token and cost usage of a request, when available.
type Usage struct {
	PromptTokens            int                       `json:"prompt_tokens"`
	CompletionTokens        int                       `json:"completion_tokens"`
	TotalTokens             int                       `json:"total_tokens"`
	Cost                    *float64                  `json:"cost"`
	CostDetails             *CostDetails              `json:"cost_details"`
	PromptTokensDetails     *PromptTokensDetails      `json:"prompt_tokens_details"`
	CompletionTokensDetails *CompletionTokensDetails  `json:"completion_tokens_details"`
	ServerToolUse           *ServerToolUse            `json:"server_tool_use"`
	CacheCreation           *AnthropicCacheCreation   `json:"cache_creation"`
	Iterations              []AnthropicUsageIteration `json:"iterations"`
	Speed                   AnthropicSpeed            `json:"speed,omitempty"`
	ServiceTier             *string                   `json:"service_tier"`
	IsBYOK                  bool                      `json:"is_byok"`
}

// CostDetails represents the breakdown of upstream inference costs.
type CostDetails struct {
	UpstreamInferenceCost            *float64 `json:"upstream_inference_cost"`
	UpstreamInferencePromptCost      float64  `json:"upstream_inference_prompt_cost"`
	UpstreamInferenceCompletionsCost float64  `json:"upstream_inference_completions_cost"`
}

// PromptTokensDetails represents the breakdown of tokens used in the prompt.
// CacheWriteTokens is only returned for models with explicit caching and cache
// write pricing.
type PromptTokensDetails struct {
	CachedTokens     *int `json:"cached_tokens"`
	CacheWriteTokens *int `json:"cache_write_tokens"`
	AudioTokens      *int `json:"audio_tokens"`
	FileTokens       *int `json:"file_tokens"`
	VideoTokens      *int `json:"video_tokens"`
}

// CompletionTokensDetails represents the breakdown of tokens generated by the
// model.
type CompletionTokensDetails struct {
	ReasoningTokens *int `json:"reasoning_tokens"`
	AudioTokens     *int `json:"audio_tokens"`
	ImageTokens     *int `json:"image_tokens"`
}

// ServerToolUse represents the usage of server-side tool execution. A
// server-orchestrated web search is counted in both ToolCallsRequested and
// WebSearchRequests, provider-native web search may report WebSearchRequests
// only, so the two must not be summed.
type ServerToolUse struct {
	ToolCallsRequested *int `json:"tool_calls_requested"`
	ToolCallsExecuted  *int `json:"tool_calls_executed"`
	WebSearchRequests  *int `json:"web_search_requests"`
}

// AnthropicCacheCreation represents the cache write tokens of a request, split
// by cache ttl.
type AnthropicCacheCreation struct {
	Ephemeral5MInputTokens int `json:"ephemeral_5m_input_tokens"`
	Ephemeral1HInputTokens int `json:"ephemeral_1h_input_tokens"`
}

// AnthropicIterationCacheCreation represents the cache write tokens of a single
// usage iteration, split by cache ttl.
type AnthropicIterationCacheCreation struct {
	Ephemeral5MInputTokens int `json:"ephemeral_5m_input_tokens"`
	Ephemeral1HInputTokens int `json:"ephemeral_1h_input_tokens"`
}

// AnthropicUsageIteration represents the usage of a single iteration of a
// request. Model is only populated for message and advisor message iterations,
// unknown iteration types are passed through as-is.
type AnthropicUsageIteration struct {
	Type                     AnthropicUsageIterationType      `json:"type"`
	Model                    string                           `json:"model,omitempty"`
	InputTokens              int                              `json:"input_tokens"`
	OutputTokens             int                              `json:"output_tokens"`
	CacheCreationInputTokens int                              `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int                              `json:"cache_read_input_tokens"`
	CacheCreation            *AnthropicIterationCacheCreation `json:"cache_creation"`
}

// InputModality is a modality a model accepts as input.
type InputModality string

const (
	InputModalityText  InputModality = "text"
	InputModalityImage InputModality = "image"
	InputModalityFile  InputModality = "file"
	InputModalityAudio InputModality = "audio"
	InputModalityVideo InputModality = "video"
)

// OutputModality is a modality a model produces as output.
type OutputModality string

const (
	OutputModalityText          OutputModality = "text"
	OutputModalityImage         OutputModality = "image"
	OutputModalityEmbeddings    OutputModality = "embeddings"
	OutputModalityAudio         OutputModality = "audio"
	OutputModalityVideo         OutputModality = "video"
	OutputModalityRerank        OutputModality = "rerank"
	OutputModalitySpeech        OutputModality = "speech"
	OutputModalityTranscription OutputModality = "transcription"
)

// ContentPartType is the type of a content part.
type ContentPartType string

const (
	ContentPartTypeImageURL ContentPartType = "image_url"
)

// ProviderSort is the sorting strategy used to pick an endpoint.
type ProviderSort string

const (
	ProviderSortPrice      ProviderSort = "price"
	ProviderSortThroughput ProviderSort = "throughput"
	ProviderSortLatency    ProviderSort = "latency"
	ProviderSortExacto     ProviderSort = "exacto"
)

// ProviderSortPartition is the partitioning strategy applied before sorting.
// Model groups endpoints by model so fallback models remain fallbacks, none
// sorts all endpoints together regardless of model.
type ProviderSortPartition string

const (
	ProviderSortPartitionModel ProviderSortPartition = "model"
	ProviderSortPartitionNone  ProviderSortPartition = "none"
)

// AnthropicSpeed is the speed tier a request was served with.
type AnthropicSpeed string

const (
	AnthropicSpeedFast     AnthropicSpeed = "fast"
	AnthropicSpeedStandard AnthropicSpeed = "standard"
)

// AnthropicUsageIterationType is the type of a single usage iteration.
type AnthropicUsageIterationType string

const (
	AnthropicUsageIterationTypeCompaction     AnthropicUsageIterationType = "compaction"
	AnthropicUsageIterationTypeMessage        AnthropicUsageIterationType = "message"
	AnthropicUsageIterationTypeAdvisorMessage AnthropicUsageIterationType = "advisor_message"
)
